paths:
  uploads: uploads
  static: ''
  collections: ''
  data: _data
  layouts: _includes
  includes: _includes
collections_config: {}
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
timezone: Etc/UTC
